###############################################################################
# SSH keypair (ED25519) generated by Terraform and saved locally.
###############################################################################

resource "tls_private_key" "ssh" {
  algorithm = "ED25519"
}

locals {
  private_key_path = "${path.module}/${var.ssh_key_dir}/${var.ssh_key_name}"
  public_key_path  = "${local.private_key_path}.pub"
}

resource "local_sensitive_file" "private_key" {
  content         = tls_private_key.ssh.private_key_openssh
  filename        = local.private_key_path
  file_permission = "0600"
}

resource "local_file" "public_key" {
  content         = tls_private_key.ssh.public_key_openssh
  filename        = local.public_key_path
  file_permission = "0644"
}
