###############################################################################
# Connection
###############################################################################

variable "libvirt_uri" {
  description = "libvirt connection URI."
  type        = string
  default     = "qemu:///system"
}

variable "pool_name" {
  description = "Name of an existing libvirt storage pool to place volumes in. The host setup script (scripts/setup-host.sh) is expected to have created it; 'default' exists on most installs."
  type        = string
  default     = "default"
}

###############################################################################
# VM
###############################################################################

variable "vm_name" {
  description = "Name (and hostname) of the sandbox VM."
  type        = string
  default     = "dev-sandbox-1"
}

variable "vcpus" {
  description = "Number of virtual CPUs for the VM."
  type        = number
  default     = 8
}

variable "memory_mb" {
  description = "Amount of RAM for the VM, in MiB."
  type        = number
  default     = 18432
}

variable "disk_size_gb" {
  description = "Size of the single merged OS+data disk, in GB."
  type        = number
  default     = 100
}

variable "ubuntu_image_url" {
  description = "URL of the Ubuntu 24.04 (Noble) cloud image. Terraform downloads this into the pool as the backing image on apply."
  type        = string
  default     = "https://cloud-images.ubuntu.com/releases/noble/release/ubuntu-24.04-server-cloudimg-amd64.img"
}

variable "timezone" {
  description = "Timezone configured inside the guest."
  type        = string
  default     = "UTC"
}

###############################################################################
# Network
###############################################################################

variable "network_name" {
  description = "Name of the libvirt NAT network to create."
  type        = string
  default     = "dev-sandbox-net"
}

variable "network_cidr" {
  description = "CIDR of the NAT network. DHCP is served from this range."
  type        = string
  default     = "10.10.10.0/24"
}

variable "network_domain" {
  description = "DNS domain for the libvirt network."
  type        = string
  default     = "sandbox.local"
}

###############################################################################
# Users
###############################################################################

variable "normal_user" {
  description = "Privileged human-developer account: full sudo, docker group, SSH."
  type        = string
  default     = "user"
}

variable "agents_user" {
  description = "Restricted AI-agent sandbox account: no sudo (docker only via sudoers), egress-firewalled, AppArmor-confined, audited."
  type        = string
  default     = "agents"
}

variable "agents_allowed_ports" {
  description = "Outbound TCP destination ports the agents user is permitted to reach. DNS (UDP/TCP 53) is always allowed."
  type        = list(number)
  default     = [22, 53, 80, 443]
}

###############################################################################
# SSH key material (generated by Terraform)
###############################################################################

variable "ssh_key_dir" {
  description = "Directory (relative to this module) where the generated SSH keypair is written."
  type        = string
  default     = ".ssh"
}

variable "ssh_key_name" {
  description = "Base filename for the generated SSH keypair."
  type        = string
  default     = "dev-sandbox_id_ed25519"
}
